title: Obinwanne Alisigwe # your name (or website title) here
logo: "/Image/Picture .png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>I’m Alisigwe Obinwanne, a data analyst with a strong background in petroleum engineering, technical analytics and project management. I recently transitioned from technical implementation roles to data analytics, driven by a passion for leveraging data to solve complex problems. My diverse experience in the oil and gas industry, combined with my recent training in data analytics, allows me to offer unique insights and data-driven solutions. I’m eager to bring my analytical skills, technical knowledge, and project management expertise to a forward-thinking company, helping drive strategic decision-making and innovation.<br>
  Second description 
  <br>Looking for ways to drive innovation and make data-informed decisions? Connect with me to explore how my skills and experiences can contribute to your team's success. Specialties data analysis, project management, technical implementation, quality assurance, Python, SQL, Tableau, MS Office. Feel free to check out my portfolio for more insights into my work and achievements.<br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
